
# Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://host.manufacturist.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build Settings
exclude: [README.md", "assets", "*.yml", "*.sh"]

plugins:
  - jekyll-feed

feed:
  path: rss/index.xml